### ISSUE TITLE
Tidak bisa push

### ISSUE THREAD

**Issue by Natanaelsinurat** [gymie/SIMoniKa#6]
![Screenshot_3](https://user-images.githubusercontent.com/55680725/69514945-98f9ea80-0f7f-11ea-8eee-28a37e6124ff.png)

**Comment by gymie** [comment]
jalankan git pull dahulu

**Comment by gymie** [comment]
jalankan 
    git pull origin master --allow-unrelated-histories

jika muncul error unrelated histories, kemudian jalankan
    git push origin master
